const GET_USERS = "GET_USERS";
const GET_USER_DETAILS = "GET_USER_DETAILS";
const CLEAR_SEARCH = "CLEAR_SEARCH";
const SET_LOADING = "SET_LOADING";
const RESET_LOADING = "RESET_LOADING";
const SET_ERROR = "SET_ERROR";

export {
    GET_USERS,
    GET_USER_DETAILS,
    CLEAR_SEARCH,
    SET_LOADING,
    RESET_LOADING,
    SET_ERROR,
};